SIP-252: simplified implementation
Synthetixio/SIPs pull request #1077
Opened 2022-06-21 01:06 UTC by artdgn

Proposed changes:
- keep flag reward transfer, and flagging mechanism as 148 - complex to implement
- simplify order of escrow entries to liquidate (first in order of iteration) - gas costs
- remove different duration of lockup - complex

2022-06-21 04:08 UTC, kaleb-keny requested changes
hey @artdgn  so my important concern here, is that if flagger/liquidator is not paid liquidation will not take place. It is vital that flag takes place even on account with no snx, just vested snx. So we need to vest token to pay for flagging/liquidation... There are many accounts with no snx in them, just escrow tokens that need to be liquidated. Unless we keep airdropping them snx to pay for flaggin this will be troublesome

2022-06-22 06:25 UTC, artdgn commented on content/sips/sip-252.md
> -- Upon liquidation / self-liquidation, the SNX relinquished by the delinquent account can be claimable by snx stakers with a `liquidationEscrowDuration` before the snx is vested. SNX Escrow entries t
will add back

2022-06-22 06:34 UTC, artdgn commented on content/sips/sip-252.md
> -#### Flag and Liquidation Mechanism
The collateral check will include the additional sources of collateral.

2022-06-22 07:59 UTC, kaleb-keny approved these changes

2022-06-22 07:59 UTC, merged