Dark mode toggle
Synthetixio/SIPs pull request #1500
Opened 2023-03-16 11:41 UTC by Ondkloss

In an effort to not get blasted with white light I made a dark mode toggle, with a tiny toggle icon in the footer.

Impementation and functionality:
* All CSS classes that included color now also have a variant that alters the color if `.dark` is higher up in the hierarchy. The `.dark` class is added to `body` when dark mode is enabled.
* The theme is stored to `localStorage` when toggled.
* It uses `dangerouslySetInnerHTML` in `html.js` to get a flicker-free theme experience.
* I've manually reviewed some SIPs with this functionality, but not all.

Notes:
* I've added no `.dark` variant for `.highlight` classes, as I'm unsure when they are used.
* Some images/graphical elements that have black lines and transparent background may not display well in dark mode.

2023-03-24 04:46 UTC, cavalier-eth commented
i love this @jmzwar or @bachstatter could you take a look?

2023-06-03 10:35 UTC, jmzwar requested changes
Works great toggling backwards and forwards but does not persist across different routes.

Thanks for the effort let me know if you need some help :)

2023-06-04 19:59 UTC, Ondkloss commented
Thanks for the review @jmzwar. I'd love to get this through, but uncertain what routes you mean, or how. 

I'm browsing the [preview by Vercel](https://sips-git-fork-ondkloss-feature-darkmode-synthetixio.vercel.app/). Are you losing theme between e.g. setting dark on the "All SIPs" page, and then clicking into a specific SIP? Or by some other specific interaction? My basic attempts at least seem to persist the theme.

2023-06-05 04:11 UTC, jmzwar commented
Hmm looks like the issue is only happening in local development.

2023-06-05 17:50 UTC, Ondkloss commented
Unable to reproduce locally with:
```
git clone https://github.com/Ondkloss/SIPs.git -b feature/darkmode SIPsDarkmode
cd SIPsDarkmode
npm install
npm start
```
I'll leave it till we figure it out. Should be dependent on `localStorage` to persist.

2023-06-09 05:03 UTC, cavalier-eth commented
@jmzwar testing in vercel i can't shake the darkmode either? surely we can ship this?

2023-06-09 05:33 UTC, jmzwar commented
Yup lgtm - only a problem with locally running. I can fix later.

Thx @Ondkloss !!

2023-06-09 05:33 UTC, jmzwar approved these changes

2023-06-09 05:44 UTC, merged