Update sccp-2138.md to Implemented
Synthetixio/SIPs pull request #2119
Opened 2024-10-13 23:04 UTC by cavalier-eth

When opening a pull request to submit a new SIP, please use the suggested template: https://github.com/Synthetixio/SIPs/blob/master/sip-X.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing Draft PRs.
 - The build passes.
 - Your Github username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2024-10-14 18:35 UTC, kaleb-keny approved these changes

2024-10-14 18:35 UTC, kaleb-keny requested changes
ohh hold on, these need a vote link, didn't forget this time 😅

2024-10-17 03:24 UTC, cavalier-eth commented
> ohh hold on, these need a vote link, didn't forget this time 😅

all added but some tests still seem to be failing?

2024-10-17 04:57 UTC, kaleb-keny commented
> > ohh hold on, these need a vote link, didn't forget this time 😅
> 
> all added but some tests still seem to be failing and it doesn't seem to be consistent

instead of 
```
proposal: >-
  https://gov.synthetix.io/#/proposal/0xc14f719687bfee53b436957bda6d631bc3f1847ce11e3f76945d49d36d46adbd
```
please use
```
proposal: >-
  https://snapshot.org/#/snxgov.eth/proposal/0xc14f719687bfee53b436957bda6d631bc3f1847ce11e3f76945d49d36d46adbd

```

snapshot works gov.synthetix doesn't

2024-10-29 08:14 UTC, closed without merging