Sip synth exchange
Synthetixio/SIPs pull request #399
Opened 2021-02-23 21:27 UTC by i-stam

2021-02-25 20:34 UTC, justinjmoses commented on sips/sip-114.md
> +interface IBaseDebtCache {
I don't think we need to define this as we're sticking with the original interface

2021-02-25 20:34 UTC, justinjmoses commented on sips/sip-114.md
> +As described in [The Optimistic Ethereum Transition](https://blog.synthetix.io/the-optimistic-ethereum-transition), phase 0 enabled users to lock snx on and mint an equivalent amount via a Syntehtix
Can you mention somewhere that this is Phase 1?

2021-02-25 20:35 UTC, justinjmoses commented on sips/sip-114.md
> +After a multi-phase, incentivised testnet trial, Synthetix went live on Optimistic Ethereum mainnet. However, this was an intitial soft launh i.e. L2 users can only stake SNX and issue or burn sUSD.
`s/launh/launch/`

2021-02-25 20:35 UTC, justinjmoses commented on sips/sip-114.md
> +As described in [The Optimistic Ethereum Transition](https://blog.synthetix.io/the-optimistic-ethereum-transition), phase 0 enabled users to lock snx on and mint an equivalent amount via a Syntehtix
`s/tarnsferable/transferable`

2021-02-25 20:35 UTC, justinjmoses commented on sips/sip-114.md
> +No new contracts were developed. The OE Synthetix instance, namely `MintableSynthetix` was enhanced with exchanging functionality. The basic Synhetix functionality that is supoorted on both layers is
`s/Synhetix/Synthetix`

2021-02-25 20:35 UTC, justinjmoses commented on sips/sip-114.md
> +No new contracts were developed. The OE Synthetix instance, namely `MintableSynthetix` was enhanced with exchanging functionality. The basic Synhetix functionality that is supoorted on both layers is
`s/imlemented/implemented`

2021-02-25 20:36 UTC, justinjmoses commented on sips/sip-114.md
> +The waiting period is now set to 0 and no rebate/reclaim takes place.
This should be removed and added into another SIP

2021-02-25 20:37 UTC, justinjmoses commented on sips/sip-114.md
> +The following functions were activated on L2 `Synthetix`:
*Are to be activated*

2021-02-25 20:37 UTC, justinjmoses commented on sips/sip-114.md
> +The polymorphic approach adopted during the L2 integration (check [SIP-102](./sip-102.md) for further details) proved to be very efficient. For basic exchanging functionality the functions needed to
Please remove the part on the waiting period here as well

2021-02-25 20:38 UTC, justinjmoses requested changes
Changes inline.

2021-02-26 14:21 UTC, ajsantander requested changes
Looks good! Suggested minor wording changes in https://github.com/Synthetixio/SIPs/pull/404

2021-02-26 17:32 UTC, ajsantander commented on sips/sip-117.md
> +author:
This section is incomplete

2021-02-26 21:51 UTC, justinjmoses approved these changes

2021-02-26 21:52 UTC, justinjmoses approved these changes
Please just create and add the discussions thread

2021-02-26 22:10 UTC, justinjmoses approved these changes

2021-02-26 22:10 UTC, merged