SIP 114 - Optimism standard deposit/withdrawal interface
Synthetixio/SIPs pull request #402
Opened 2021-02-25 14:48 UTC by ajsantander

Proposal to update our bridges to conform to the standard interface being proposed by Optimism.

2021-02-25 22:39 UTC, jacko125 commented on sips/sip-115.md
> +This is where you explain the reasoning behind how you propose to solve the problem. Why did you propose to implement the change in this way, what were the considerations and trade-offs. The rational
@ajsantander Should this be removed / uncommented?

2021-02-26 00:34 UTC, justinjmoses commented on sips/sip-115.md
> +sip: 115
can you use 116? :pray:

2021-02-26 00:34 UTC, justinjmoses commented on sips/sip-115.md
> +created: <date created on, in ISO 8601 (yyyy-mm-dd) format>
please add this

2021-02-26 00:34 UTC, justinjmoses commented on sips/sip-115.md
> +requires (*optional): <SIP number(s)>
this can be removed

2021-02-26 00:34 UTC, justinjmoses commented on sips/sip-115.md
> +The proposed changes involve renaming a few functions and events in two of our contracts, namely SynthetixBridgeToOptimism and SynthetixBridgeToBase, as well as adding minor functionality to them to
[np] please use backticks for contract names

2021-02-26 00:35 UTC, justinjmoses commented on sips/sip-115.md
> +This is a high level overview of *how* the SIP will solve the problem. The overview should clearly describe how the new feature will be implemented.
this line is not needed

2021-02-26 00:39 UTC, justinjmoses requested changes
Some minor changes 🙏🏼

2021-02-26 17:41 UTC, ajsantander commented
Deprecating in favor of https://github.com/Synthetixio/SIPs/pull/405

2021-02-26 17:41 UTC, closed without merging