SIP-172 Governance v2
Synthetixio/SIPs pull request #646
Opened 2021-08-03 15:17 UTC by justinjmoses

This proposal seeks to elevate the current Synthetix Governance System, addressing pain points that have been identified during the first version of governance as well as proposing new processes and tools to improve the self-autonomy and efficiency of the Synthetix DAOs.

2021-08-03 16:05 UTC, gberg1 approved these changes

2021-08-04 17:53 UTC, gberg1 requested changes
Think we need to address and define the problems in the SIP in addition to stating that there are problems

2021-08-04 17:53 UTC, gberg1 commented on sips/sip-172.md
> +We have identified ‘inefficiencies’ that are negatively impacting on the overall Governance process and user experience of the Synthetix community. This SIP aims to address these ‘inefficiencies’ and
@andytcf @CryptoToit can you describe the inefficiencies in more detail?

2021-08-04 17:53 UTC, gberg1 commented on sips/sip-172.md
> +This proposal seeks to elevate the current Synthetix Governance System, addressing pain points that have been identified during the first version of governance as well as proposing new processes and
@andytcf @CryptoToit see below comment. Feel we should describe the problems in more detail in the SIP

2021-08-18 13:05 UTC, dgornjakovic approved these changes

2021-08-18 15:48 UTC, gberg1 approved these changes

2021-08-18 15:48 UTC, merged