Update SIP-148 with liquidation escrow duration SCCP value
Synthetixio/SIPs pull request #899
Opened 2022-02-23 16:55 UTC by barrasso

2022-02-23 18:56 UTC, kaleb-keny requested changes
hey @barrasso i think we agreed on a 24 hours delay, not 12 hours

2022-02-23 18:57 UTC, kaleb-keny requested changes
Also could we have the optimism rewards set below... i think it was 2 snx maybe only

2022-03-02 18:43 UTC, barrasso commented
updated sccp values @kaleb-keny

2022-03-03 11:34 UTC, kaleb-keny approved these changes

2022-03-03 11:34 UTC, merged